raw_dtypes = {
    'CD_ORGAO': 'object',
    'NM_ORGAO': 'object',
    'NR_LICITACAO': 'float64',
    'ANO_LICITACAO': 'object',
    'CD_TIPO_MODALIDADE': 'object',
    'NR_COMISSAO': 'float64',
    'TP_OBJETO': 'object',
    'CD_TIPO_FASE_ATUAL': 'object',
    'TP_LICITACAO': 'object',
    'TP_NIVEL_JULGAMENTO': 'object',
    'TP_CARACTERISTICA_OBJETO': 'object',
    'TP_NATUREZA': 'object',
    'DS_OBJETO': 'object',
    'VL_LICITACAO': 'object',
    'BL_PERMITE_CONSORCIO': 'object',
    'DT_ABERTURA': 'object',
    'DT_HOMOLOGACAO': 'object',
    'DT_ADJUDICACAO': 'object',
    'BL_LICIT_PROPRIA_ORGAO': 'object',
    'VL_HOMOLOGADO': 'object',
    'DS_OBSERVACAO': 'object'
}
