# import polars as pl

# raw_dtypes = {
#     "CD_ORGAO": "object",
#     "NM_ORGAO": "object",
#     "NR_LICITACAO": "float64",
#     "ANO_LICITACAO": "object",
#     "CD_TIPO_MODALIDADE": "object",
#     "NR_COMISSAO": "float64",
#     "TP_OBJETO": "object",
#     "CD_TIPO_FASE_ATUAL": "object",
#     "TP_LICITACAO": "object",
#     "TP_NIVEL_JULGAMENTO": "object",
#     "TP_CARACTERISTICA_OBJETO": "object",
#     "TP_NATUREZA": "object",
#     "DS_OBJETO": "object",
#     "VL_LICITACAO": "object",
#     "BL_PERMITE_CONSORCIO": "object",
#     "DT_ABERTURA": "object",
#     "DT_HOMOLOGACAO": "object",
#     "DT_ADJUDICACAO": "object",
#     "BL_LICIT_PROPRIA_ORGAO": "object",
#     "VL_HOMOLOGADO": "object",
#     "DS_OBSERVACAO": "object",
# }

raw_dtypes = {
    "CD_ORGAO": "object",
    "NM_ORGAO": "object",
    "NR_LICITACAO": "object",
    "ANO_LICITACAO": "object",
    "CD_TIPO_MODALIDADE": "object",
    "NR_COMISSAO": "object",
    "TP_OBJETO": "object",
    "CD_TIPO_FASE_ATUAL": "object",
    "TP_LICITACAO": "object",
    "TP_NIVEL_JULGAMENTO": "object",
    "TP_CARACTERISTICA_OBJETO": "object",
    "TP_NATUREZA": "object",
    "DS_OBJETO": "object",
    "VL_LICITACAO": "object",
    "BL_PERMITE_CONSORCIO": "object",
    "DT_ABERTURA": "object",
    "DT_HOMOLOGACAO": "object",
    "DT_ADJUDICACAO": "object",
    "BL_LICIT_PROPRIA_ORGAO": "object",
    "VL_HOMOLOGADO": "object",
    "DS_OBSERVACAO": "object",
}



# raw_schema = {
#     "CD_ORGAO": pl.String,
#     "NM_ORGAO": pl.String,
#     "NR_LICITACAO": pl.Float64,
#     "ANO_LICITACAO": pl.String,
#     "CD_TIPO_MODALIDADE": pl.String,
#     "NR_COMISSAO": pl.Float64,
#     "TP_OBJETO": pl.String,
#     "CD_TIPO_FASE_ATUAL": pl.String,
#     "TP_LICITACAO": pl.String,
#     "TP_NIVEL_JULGAMENTO": pl.String,
#     "TP_CARACTERISTICA_OBJETO": pl.String,
#     "TP_NATUREZA": pl.String,
#     "DS_OBJETO": pl.String,
#     "VL_LICITACAO": pl.Float64,
#     "BL_PERMITE_CONSORCIO": pl.String,
#     "DT_ABERTURA": pl.String,
#     "DT_HOMOLOGACAO": pl.String,
#     "DT_ADJUDICACAO": pl.String,
#     "BL_LICIT_PROPRIA_ORGAO": pl.String,
#     "VL_HOMOLOGADO": pl.String,
#     "DS_OBSERVACAO": pl.String,
# }
